### ISSUE TITLE
Is there an option to remove local Umbraco media files?

### ISSUE THREAD

**Issue by gemmadlou** [AliSheikhTaheri/AST-Amazon-S3#1]
Is there an option to remove local Umbraco media files?

So that when the Umbraco media files are uploaded to S3, it is not uploaded also to the Umbraco CMS, but can be viewed from the Amazon S3 Bucket?

**Comment by AliSheikhTaheri** [comment]
No, This package saves the files locally and then transfer them to S3.

**Comment by gemmadlou** [comment]
Thanks Ali
